# Generated by Django 4.2.2 on 2023-06-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodDonateApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonatedata',
            name='sl_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
