# Generated by Django 4.2.2 on 2023-06-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodDonateApp', '0002_alter_blooddonatedata_sl_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonatedata',
            name='age',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
