# Generated by Django 4.2.2 on 2023-06-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodDonateApp', '0003_alter_blooddonatedata_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonatedata',
            name='blood_group',
            field=models.CharField(choices=[('A +', 'A +'), ('A -', 'A -'), ('B +', 'B +'), ('B -', 'B -'), ('O +', 'AB +'), ('AB -', 'AB -'), ('O +', 'O +'), ('O -', 'O -')], default='AB +', max_length=100),
        ),
        migrations.AlterField(
            model_name='blooddonatedata',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Female', max_length=100),
        ),
    ]
