# Generated by Django 4.2.2 on 2023-06-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodDonateApp', '0004_alter_blooddonatedata_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonatedata',
            name='blood_group',
            field=models.CharField(choices=[('A +', 'A +'), ('A -', 'A -'), ('B +', 'B +'), ('B -', 'B -'), ('AB +', 'AB +'), ('AB -', 'AB -'), ('O +', 'O +'), ('O -', 'O -')], default='AB +', max_length=100),
        ),
    ]
